const FETCH_NOTES_INIT = "FETCH_NOTES_INIT";
const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export { FETCH_NOTES_FAILURE, FETCH_NOTES_INIT, FETCH_NOTES_SUCCESS };
